config/routes.rb
  ActionController::Routing::Routes.draw do |map|
    
  map.namespace :asset_manager do |manager|    
    manager.resources :assets, :collection => { :select_stage => :post, :deselect_stage => :post },
                      :has_many => [:captions, :credits, :tags]
    manager.resources :stages, :collection => {:add_asset_to_stage => :put },
                      :member => { :manage_users => :get, :add_user => :post, :remove_user => :post,
                      :contract => :get, :agree => :get,
                      :remove_asset_from_stage => :put }
    manager.resources :languages
    manager.resources :tribes
    manager.resources :countries
    manager.resources :contracts
    manager.resources :credits
    manager.resources :captions
    manager.resources :tags
    
    manager.resources :asset_users
    manager.resources :asset_user_sessions
    manager.login "login", :controller => :asset_user_sessions, :action => :new
    manager.logout "logout", :controller => :asset_user_sessions, :action => :destroy
    
    manager.root :controller => :asset_user_sessions, :action => :new
  end

  map.resources :admin_users
  map.resources :admin_user_sessions
  map.login "login", :controller => :admin_user_sessions, :action => :new
  map.logout "logout", :controller => :admin_user_sessions, :action => :destroy
  map.root :controller => "AssetManager::Assets"
  
end

app/models/asset.rb
# Asset model handles storage of assets using Paperclip, extraction of EXIF data using exifr,
# processes virtual attributes for AJAX forms, contains search method and settings for
# pagination of asset collections
 
class Asset < ActiveRecord::Base
  # Method from declarative authorization that allows permission based filtering
  # for models.
  using_access_control
  
  # Polymorphic association between asset and image models allows for
  # Asset#exif to be called regardless is asset exif/metadata is stored in
  # different tables.
  belongs_to :exif, :polymorphic => true, :dependent => :destroy
  
  belongs_to :country
  belongs_to :tribe

  has_many :captions, :dependent => :destroy
  accepts_nested_attributes_for :captions
  has_many :credits, :dependent => :destroy

  has_and_belongs_to_many :tags
  has_and_belongs_to_many :stages

  validates_presence_of :tribe
  validates_presence_of :country

  # Uploading Images Using Paperclip
  has_attached_file	:data,
			:url => "/assets/images/:id/:style/:basename.:extension",
			#:path => "#{RAILS_ROOT}/public/images/:id/:style/:basename.:extension",

  # Resizing Images
  #For windows systems, the greater than sign '>' must be escaped with the hat '^' symbol
  #The '^' is not required on *nix systems
  :styles => {:thumb => ["193x120", :jpg], :medium => ["350x350", :jpg], :large => ["540x337", :jpg]}

  # Connection to S3
  #:storage => :s3,
  #:s3_credentials => "#{RAILS_ROOT}/config/s3.yml",
  #:s3_options => {:proxy => {:host => 'proxy.abdn.ac.uk', :port => 8080} }, #note to team: if working from home
                                                                             #comment out :s3_options then restart server
  
  # A "canned" S3 access policy, authenticated read prevents unauthenticated
  # users from viewing assets.
  #:s3_permissions => 'authenticated-read',
  #:bucket => "survival-project"

  # Checking Filetypes
  validates_attachment_presence :data
  validates_attachment_content_type :data, :content_type => ["image/jpeg", "image/png", "image/bmp", "image/tiff", "image/pjpeg", "image/x-png", "image/jpg"]

  # Sets EXIF data for asset before uploading to Amazon S3
  after_post_process :set_exif_data

  # Saves tags and captions updated in virtual attributes
  after_update :save_tags, :save_captions, :save_credits

  # Pagination: assets per page
  cattr_reader :per_page
  @@per_page = 12

  # Asset search function
  def self.search(search, page)
    paginate 	:per_page => 12, :page => page,
      :conditions => ['title like ?', "%#{search}%"],
      :order => 'title'
  end


  ## Start of EXIF code ##

  # Returns true if asset has EXIF data associated
  def exif?
    return true if not exif_type.nil?
    rescue
      false
  end

  # Method called by paperclip callback.  Looks at asset type and determines
  # which method to use to set EXIF data
  def set_exif_data
    if data_content_type =~ /^image.*/
      if data_content_type =~ /jpeg/
        set_image_exif_data
      end
    end
  end

  ## Start of virtual attributes and save methods for AJAX forms ##

  # Virtual attribute setter method for updating tags via AJAX forms.
  # Only updates tags currently associated to asset.
  def updated_tag_attributes=(tag_attributes)
    tags.reject(&:new_record?).each do |tag|
      attributes = tag_attributes[tag.id.to_s]
      if attributes
        if(attributes[:content].eql? tag[:content])
          #do nothing
        else
          new_tag = Tag.find_or_create_by_content(attributes[:content])
          if(tags.exists?(new_tag))
            #do nothing
          else
            tags.delete(tag)
            tags << new_tag
          end
        end
      else
        tags.delete(tag)
      end
    end
  end

  # Virtual attribute setter method for associating new tags to asset via
  # AJAX forms.  Prevents user from associating the same tag multiple times
  # to an asset.
  def new_tag_attributes=(tag_attributes)
    new_tags = Set.new

    tag_attributes.each do |a|
      new_tags.add(a)
    end

    new_tags.each do |nt|
      if nt[:content].eql? ""
        #do nothing
      else
        tag = Tag.find_or_create_by_content(nt[:content])
        if !tags.exists?(tag)
          tags << tag #self.tags
        end
      end
    end
  end

  # Method used in ActiveRecord callback to ensure new and updated tags are
  # saved.
  def save_tags
    tags.each do |tag|
      tag.save(false)
    end
  end

  # Virtual attribute setter method for updating captions via AJAX forms.
  # Only updates captions currently associated to asset.
  def updated_caption_attributes=(caption_attributes)
    captions.reject(&:new_record?).each do |caption|
      attributes = caption_attributes[caption.id.to_s]
      if attributes
        caption.attributes = attributes
      else
        captions.delete(caption)
      end
    end
  end

  # Virtual attribute setter method for associating new captions to asset via
  # AJAX forms.
  def new_caption_attributes=(caption_attributes)
    caption_attributes.each do |a|
      captions.build(a)
    end
  end

  # Method used in ActiveRecord callback to ensure new and updated captions are
  # saved.
  def save_captions
    captions.each do |caption|
      caption.save(false)
    end
  end

  # Virtual attribute setter method for updating credits via AJAX forms.
  # Only updates credits currently associated to asset.
  def updated_credit_attributes=(credit_attributes)
    credits.reject(&:new_record?).each do |credit|
      attributes = credit_attributes[credit.id.to_s]
      if attributes
        credit.attributes = attributes
      else
        credits.delete(credit)
      end
    end
  end

  # Virtual attribute setter method for associating new credits to asset via
  # AJAX forms.
  def new_credit_attributes=(credit_attributes)
    credit_attributes.each do |a|
      credits.build(a)
    end
  end

  # Method used in ActiveRecord callback to ensure new and updated credits are
  # saved.
  def save_credits
    credits.each do |credit|
      credit.save(false)
    end
  end

  private
  
  ## When asset is found to be a JPEG image, attempts to extract EXIF data
  def set_image_exif_data
    exif_data = EXIFR::JPEG.new(data.to_file.path)
    return if exif_data.nil? or not exif_data.exif?
      i = Image.new
      i.width            = exif_data.width
      i.height           = exif_data.height
      i.camera_brand     = exif_data.make.to_s
      i.camera_model     = exif_data.model.to_s
      i.exposure_time    = exif_data.exposure_time.to_s
      i.f_number         = exif_data.f_number.to_f
      i.iso_speed_rating = exif_data.iso_speed_ratings
      i.shot_date_time   = exif_data.date_time
      i.focal_length     = exif_data.focal_length.to_f
      self.exif = i
      i.save!
    rescue
      false
  end

end

app/models/tag.rb
# Model front end for tags table

class Tag < ActiveRecord::Base
  # Method from declarative authorization that allows permission based filtering
  # for models.
  using_access_control
  
  has_and_belongs_to_many :assets
end

app/controllers/asset_manager/assets_controller.rb
# Assets controller handles actions relating to assets, actions for
# selecting and deselecting stages and a method for filtering out
# extraneous EXIF data before it is displayed on a show page

class AssetManager::AssetsController < AssetManager::ApplicationController
  # Declarative authorization method to enable permissions based filtering of
  # actions.  Doesn't automatically load assets.
  filter_access_to :all
  
  # Provides access to s3_authenticated_url in views
  helper AssetManager::AssetsHelper
  
  # GET /assets
  # GET /assets.xml
  def index
    @assets = Asset.search(params[:search], params[:page])
    @stages = Stage.find(:all)

    respond_to do |format|
       format.html #index.html.erb
       format.xml { render :xml => @assets }
    end
  end

  # GET /assets/1
  # GET /assets/1.xml
  def show
    @asset = Asset.find(params[:id])
    if @asset.exif?
    	@exif = @asset.exif.attributes
    	@exif = format_exif(@exif)
   end
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => asset_manager_asset_path(@asset) }
    end
  end
  
  # GET /assets/new
  # GET /assets/new.xml
  def new
    @asset = Asset.new
    @countries = Country.find(:all)
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @asset }
    end
  end

  # GET /assets/1/edit
  def edit
    @asset = Asset.find(params[:id])
    @countries = Country.find(:all)
    @tags = @asset.tags
  end

  # POST /assets
  # POST /assets.xml
  def create
    @asset = Asset.new(params[:asset])
    @countries = Country.find(:all)
    
    respond_to do |format|
      if @asset.save
        format.html { redirect_to(asset_manager_asset_path(@asset), :notice => 'Asset was successfully created.') }
        format.xml  { render :xml => @asset, :status => :created, :location => @asset }
      else
        format.html { render :action => :new, :notice => 'Asset was not created.' }
        format.xml  { render :xml => @asset.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /assets/1
  # PUT /assets/1.xml
  def update
    # If attributes are empty i.e. all removed, returns empty hash
    params[:asset][:updated_tag_attributes] ||= {}
    params[:asset][:updated_caption_attributes] ||= {}
    params[:asset][:updated_credit_attributes] ||= {}
    @asset = Asset.find(params[:id])
    
    respond_to do |format|
      if @asset.update_attributes(params[:asset])
        format.html { redirect_to(asset_manager_asset_path(@asset), :notice => 'Asset was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => :edit }
        format.xml  { render :xml => @asset.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.xml
  def destroy
    @asset = Asset.find(params[:id])
    @asset.destroy
    
    respond_to do |format|
      format.html { redirect_to(asset_manager_assets_path) }
      format.xml  { head :ok }
    end
  end
  
  # POST /assets/select_stage
  #
  # Action that, provided a stage ID has been passed, assigns that stage ID
  # to a session which is stored locally on the user's system
  def select_stage
    if !params[:stage][:id].empty?
      session[:stage_id] = params[:stage][:id].to_i
      redirect_to :back, :notice => "You can now add assets to #{Stage.find(session[:stage_id]).title}"
    else
      redirect_to :back, :notice => "No stage was selected"
    end
  end
  
  # POST /assets/deselect_stage
  #
  # Action that sets the stage ID in session to nil
  def deselect_stage
    session[:stage_id] = nil
    redirect_to :back, :notice => "Please select a different stage"
  end
  
  private
  
  # Method that filters EXIF data:
  #
  # * Removes the ID field, fields with values equal to 0.0 
  #   (specifically the focal length,) and blank values.
  #
  # * Humanizes the output by replacing underscores and capitalizing.
  #
  # * Formats time string to a more readable format.
  def format_exif(exif)
    exif.reject! { |key,value| (key.eql? "id") || (value == 0.0) || (value.blank?) }
	    
    exif.each_pair { |key,value| 
    new_key = key.to_s.dup
    new_key.gsub!("_", " ")
    new_key.capitalize!

    if new_key.eql? "Shot date time"
      new_value = @asset.exif.shot_date_time.strftime("%d %b %Y %H:%M")
    else
      new_value = value.to_s.dup
    end

    exif.delete(key)
    exif.store(new_key, new_value) }
    
    return exif
  end

end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_filter :verify_credentials
  
  # GET /assets
  # GET /assets.xml
  def index
    @assets = Asset.search(params[:search], params[:page])
     @stages = Stage.find(:all)
    respond_to do |format|
       format.html #index.html.erb
       format.xml { render :xml => @assets }
    end
  end
  
  def gallery
    @assets = Asset.search(params[:search], params[:page])
        @stages = Stage.find(:all)
  end

  # GET /assets/1
  # GET /assets/1.xml
  def show
    @asset = Asset.find(params[:id])
    if @asset.exif?
    	@exif = @asset.exif.attributes
    end
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @asset }
    end
  end
  
  # GET /assets/new
  # GET /assets/new.xml
  def new
    @asset = Asset.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @asset }
    end
  end

  # GET /assets/1/edit
  def edit
    @asset = Asset.find(params[:id])
  end

  # POST /assets
  # POST /assets.xml
  def create
    @asset = Asset.new(params[:asset])
    
    respond_to do |format|
      if @asset.save
        @asset.set_exif_data
        
        format.html { redirect_to(@asset, :notice => 'Asset was successfully created.') }
        format.xml  { render :xml => @asset, :status => :created, :location => @asset }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @asset.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /assets/1
  # PUT /assets/1.xml
  def update
    @asset = Asset.find(params[:id])
    
    respond_to do |format|
      if @asset.update_attributes(params[:asset])
        format.html { redirect_to(@asset, :notice => 'Asset was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @asset.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.xml
  def destroy
    @asset = Asset.find(params[:id])
    @asset.destroy
    
    respond_to do |format|
      format.html { redirect_to(assets_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/asset_manager/assets_helper.rb
module AssetManager::AssetsHelper
  # Helper generates authenticated URL for sending requests to S3 to download
  # assets.
  def s3_authenticated_url(asset, style, expires=10.seconds, ssl=false)
    AWS::S3::S3Object.url_for(asset.data.path(style), asset.data.bucket_name, :expires_in => expires, :use_ssl => ssl)
  end
end

app/views/assets/gallery.html.erb
<% title "Image Gallery" %>
<div>
  <% form_tag 'gallery', :method => 'get' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  <% end %>
</div>
<div id="gallery_container">
  <div id="image_gallery">
  <% form_tag added_stages_path, :method => :put do %>
    <% @assets.each do |asset| %>
      <div class="thumbnail">
        <%= link_to image_tag(asset.data.url(:thumb)), asset %><br/>
        <%= link_to asset.title, asset %>
        <%= check_box_tag "asset_ids[]", asset.id %>
      </div>
    <% end %>
    <h2> Select a Stage to Add the Assets to </h2>
    <p><%= collection_select(:stage, :stage_id, Stage.all, :id, :title, {:prompt => true}) %>
    <p><%= submit_tag "Add To Stage" %>
    <% end %>
    
    
  </div>
</div>
<div class="clear">
  <div>
    <%= will_paginate @assets %>
  </div>
  <%= link_to "Create new asset", :action => "new" %> | <%= link_to 'Back', assets_path %>
</div>





 

app/views/assets/index.html.erb
<% title "Home Page" %>
<h2>Welcome To Your Asset Archive</h2>
<p> In your asset archive, you can edit and delete your current assets as well as add new ones. </p>
<p> You can also search through your archive by entering search criteria in the box below </p>

<div class="search">
<% form_tag assets_path, :method => 'get' do %> 
<%= text_field_tag :search, params[:search] %>
 <%= submit_tag "Search", :name => nil %> 
</div>
<% end %>
<table>
  <tr>
    <th>Your Assets:</th>
  </tr>

<% @assets.each do |asset| %>
  <tr>
    <td><%=h asset.title %></td>
    <td><%= link_to 'Show', asset %></td>
    <td><%= link_to 'Edit', edit_asset_path(asset) %></td>
    <td><%= link_to 'Destroy', asset, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<div class="will_paginate_assetslist">
<%= will_paginate @assets %>
</div>

<h2> Add A New Asset </h2>
<div class="assetslink">
<%= link_to 'New asset', new_asset_path %> </div>
<h2> View All Images </h2>
<div class="assetslink">
<%= link_to "View Gallery", :action => "gallery" %>
<h2> View List of Stages</h2>
<%= link_to "View Stages", stages_path %>
<h2> Drop Down of Stages </h2>
<%= select(:stage_id, :title, @stages.collect {|s|[s.title, s.id]}) %>

</div>

app/views/assets/new.html.erb
<% title "New Asset" %>
<h4>Adding A New Asset</h4>
<% form_for(@asset, :html => { :multipart => true } ) do |f| %>
  <%= f.error_messages %>
  <h4>Step 1: Give Your Asset a Title</h4>
  <div>
    <%= f.text_field :title %>
  </div>
  <h4>Step 2: Browse Your Files For The New Asset </h4>
  <div>
    <%= f.file_field :data %>
  </div>
  

  <h4>Step 3: Click Upload To Submit Your Asset</h4>
  <div>
    <%= f.submit 'Upload' %>
  </div>
<% end %>
<div><%= link_to 'Back', assets_path %></div>

app/views/assets/show.html.erb
<%  title "Viewing #{@asset.title}" %>
<div id="show_left_column">
	<div id="show_pic_asset">
		<%= image_tag @asset.data.url(:large) %>
	</div>
</div>
<div id="show_right_column">
	<ul class="picAttributes">
  	<li><strong>Title: </strong><%=h @asset.title %></li>
    <li><strong>File Name: </strong><%=h @asset.data_file_name %></li>
    <li><strong>File Type: </strong><%=h @asset.data_content_type %></li>
    <li><strong>Date Created: </strong><%=h @asset.created_at %></li>
    <li><strong>Last Updated: </strong><%=h @asset.updated_at %></li>

  <% if @asset.exif? %>
   	<% @exif.each_pair { |key, value| %>
    <li><strong><%= "#{key}: " %></strong><%= "#{value}" %></li>
    <% } %>
	<% end %>
	</ul>  
</div>

<div id="footer">
	<%= link_to 'Tag Asset', new_tag_path(@asset) %>
	<%= link_to 'Edit', edit_asset_path(@asset) %> |
  <%= link_to 'Back', assets_path %>
</div>

app/views/assets/view.html.erb
<html> 
  <head>
    <title>Image Gallery</title>
  </head>
  <body>
   
  <h1>Gallery</h1>
  <table border="0">
  <tr>
  <td width="80%"><p align="center"><i><b>Asset</b></i></td> 
  </tr>
    
  <% @assets.each do |asset| %>
  <tr>
  <td>
  <%= image_tag asset.file.url(:thumb) %>
  <br/>
  <%=h asset.title %>
</p>
    </td>
 
 
  </tr>
  <% end %> 
  </table>
  <p><%= link_to "Create new asset", :action => "new" %> | <%= link_to 'Back', assets_path %> </p>

  </body> 
</html>